DROP TABLE IF EXISTS birds;

CREATE TABLE birds (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  flies BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS flowers;

CREATE TABLE flowers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  color TEXT NOT NULL,
  petals INT NOT NULL
);

DROP TABLE IF EXISTS trees;

CREATE TABLE trees (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  family TEXT NOT NULL,
  elevation INT NOT NULL
);

DROP TABLE IF EXISTS butterflies;

CREATE TABLE butterflies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  food TEXT NOT NULL,
  color TEXT NOT NULL
);